os: linux
dist: bionic
language: python
python:
  - 3.8
services:
  - docker
env:
  - STAGE=prod
  - STAGE=karma
  - STAGE=cypress BROWSER=chrome
  # it stucks quite often... to be retried in a near future
  # - STAGE=cypress BROWSER=firefox
  - STAGE=cypress BROWSER=electron
  # - STAGE=cypress BROWSER=chromium

script:
  - export CURRENT_VERSION=$(grep '"version"' src/package.json | awk {'print $2'} | tr -d '", ')
  - pip3 install --upgrade git+https://github.com/rapydo/do.git@${CURRENT_VERSION}
  - mkdir rapydo_tests
  - cd rapydo_tests
  - rapydo create prj --auth postgres --frontend angular --origin https://your_remote_git/your_project.git;
  - >
    if [[ "$STAGE" == "karma" ]]; then

      TESTING=1 rapydo init
      rapydo -s frontend pull;
      rapydo -s frontend start;
      sleep 5;
      rapydo shell frontend --command "yarn install" || travis_terminate 1;
      rapydo shell frontend --command "yarn run test:single" || travis_terminate 1;
      cp data/prj/karma/lcov.info .;
      bash <(curl -s https://codecov.io/bash) -R submodules/frontend;

    elif [[ "$STAGE" == "prod" ]]; then

      rapydo --prod init
      rapydo -s frontend pull;
      rapydo -s frontend start;
      rapydo dump;
      rapydo -s frontend logs --follow;
      docker-compose logs --tail 2 frontend 2>&1 | grep "files have been compressed.";

    else

      TESTING=1 rapydo init

      cd submodules/frontend;
      export COMMIT_INFO_BRANCH="$(git rev-parse --abbrev-ref HEAD)";
      export COMMIT_INFO_MESSAGE="$(git show -s --pretty=%B)";
      export COMMIT_INFO_SUBJECT="$(git show -s --pretty=%s)";
      export COMMIT_INFO_BODY="$(git show -s --pretty=%b)";
      export COMMIT_INFO_EMAIL="$(git show -s --pretty=%ae)";
      export COMMIT_INFO_AUTHOR="$(git show -s --pretty=%an)";
      export COMMIT_INFO_SHA="$(git show -s --pretty=%H)";
      export COMMIT_INFO_TIMESTAMP="$(git show -s --pretty=%ct)";
      export COMMIT_INFO_REMOTE="$(git config --get remote.origin.url)";
      export CYPRESS_GROUP="$(git show -s --pretty=%H)";
      cd -;

      rapydo pull;
      rapydo start;
      rapydo shell backend --command 'restapi wait';
      rapydo shell backend --detach --command "restapi launch";
      rapydo shell frontend --command "yarn install" || travis_terminate 1;
      rapydo shell frontend --command "yarn run cypress:start:${BROWSER}" || travis_terminate 1;
      rapydo shell frontend --command "npx nyc report --reporter=lcov" || travis_terminate 1;
      cp data/prj/karma/lcov.info .;
      bash <(curl -s https://codecov.io/bash) -R submodules/frontend;

    fi

notifications:
  email: false
  slack:
    rooms:
      secure: FPS8zIxMpBBE4RvU/aGIaXrBM41WosjGdVEaEOLtws5ofoK28is4QNkeI1WyQoXcij7noPfcGY+TSacgFr7/MQP2LzO0bo77WIQYab1vFjM5pFtgll8nBINXTy84ND6oOKOvD04wnrnUcD5X9TlITtI5/brgeb91Fm21jWnbsd8iYr0PfbqfvuE6HG7MDKzE5IbyIE1b3IltZyRwnH1nMhCTohCqiK3l8JwxY3DGV72kWGPF6uKXV6J087F1exRBCEfaJAIkCM14Sw6KFX5ATAfjXmRm3phR4Iv2NpOqdHAwOnWHqbXtNkONvN8/G/5xmGQ1BQJVpVxzCVw8fphToEPbyjqIJ6ZE+zKKl7TRAOCWcwX8DpROfBtLXi04g5X5DS7+ZFL1xnb0R6/DC8CsvPWe6096UfzTvpFQANeJ6pK5YKZECzU5/FKUMx/F6leLRWIqbkkkrXmhvjZ29GABx4zpWfAqU1sj5K7XG6OcihGnXXgdViDmqYyC7sxln+MMDM5xMZSRS/5eEusSMn49crmc5DidyJiZo7r2uS5fHXQ3dBVFYv240g7bc9QJHk6DbnCSz6zPfjUQbauhjJt9+akot0AX6yhwwwusslctCxRTdzvPzdy8BkQ7rHJbjCnVLlP30+uEUpwp8pRf8rq8kOSuF6o+YVYlzA8v+O649a8=
    on_success: change # default: always
    on_failure: always # default: always
